### ISSUE TITLE
better support RDF*

### ISSUE THREAD

**Issue by joylix** [giacomociti/rdf2dot#1]
The W3C's  RDF* specification is  nearing completion， It is supported by a growing number of graph databases, 

The latest spec version is at:     https://w3c.github.io/rdf-star/cg-spec/editors_draft.html    
 what is RDF*:                    https://enterprise-knowledge.com/rdf-what-is-it-and-why-do-i-need-it/     

It would be great if we could use rdf2dot to handle RDF* file.

Regards,

**Comment by giacomociti** [comment]
This tool is based on dotnetrdf which, if I’m not wrong, does not support RDF* yet. In any case I don’t know how to decently render RDF* visually and I’m afraid it is beyond the (admittedly modest) scope of this tool (but I’m glad to accept contributions to improve and expand it).

**Comment by giacomociti** [comment]
The project is now based on javascript and notation 3. Although the general purpose visualization rules provided in the [playground page](https://giacomociti.github.io/rdf2dot/) ignore rdf-star, it is possible to use custom visualization rules.

For example, using the test data:
```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix : <http://example.org/> .

<<:ann :knows :bob>> :startDate "2020"^^xsd:gYear .
<<:ann :knows :alice>> :startDate "2021"^^xsd:gYear .
```
the following diagram:

![star](https://github.com/giacomociti/rdf2dot/assets/7202774/495c517d-b78e-4e2b-985b-ec11a6d18d5d)

is obtained with the custom rules:

```turtle
@prefix string: <http://www.w3.org/2000/10/swap/string#> .
@prefix log: <http://www.w3.org/2000/10/swap/log#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix v: <http://view/> .
@prefix attr: <http://view/dot/attribute/> .
@prefix : <http://example.org/> .

{
   <<?s :knows ?o>> :startDate ?d .
   (?date ?dataType) log:dtlit ?d .
   ("knows\n(since %s)" ?date) string:format ?label .
}
=>
{
    v:digraph v:hasNode ?s , ?o .
    v:digraph v:hasEdge [ v:source ?s ; v:target ?o ; attr:label ?label ] .
}
.
```

**Comment by joylix** [comment]
In the nodes of the above diagram, how to  omit the namespace http://example.org/ann and display only ann ?

**Comment by giacomociti** [comment]
there is a convenient N3 built-in called [`log:localName`](https://github.com/eyereasoner/Notation3-By-Example/blob/main/log/localName.n3) to extract the last URI segment.

```turtle
@prefix string: <http://www.w3.org/2000/10/swap/string#> .
@prefix log: <http://www.w3.org/2000/10/swap/log#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix v: <http://view/> .
@prefix attr: <http://view/dot/attribute/> .
@prefix : <http://example.org/> .

{
   <<?s :knows ?o>> :startDate ?d .
   (?date ?dataType) log:dtlit ?d .
   ("knows\n(since %s)" ?date) string:format ?label .
   ?s log:localName ?subjectName .
   ?o log:localName ?objectName .
}
=>
{
    ?s attr:label ?subjectName .
    ?o attr:label ?objectName .
    v:digraph v:hasNode ?s , ?o .
    v:digraph v:hasEdge [ v:source ?s ; v:target ?o ; attr:label ?label ] .
}
.
```

**Comment by joylix** [comment]
Thank you very much!
I used the online demo page to test this rdf-star example, and I only got the right graph as in this page by chance. Other times, I couldn't reproduce this picture no matter if I used default or basic mode.  
in basic mode , it shows :  http://eyereasoner.github.io/.well-known/genid/1dce87d2-65bb-4c85-879a-21acc4202221#t_0
In default mode, it only displays:  startDate 2020    startDate 2021

**Comment by giacomociti** [comment]
neither default nor basic mode can show quoted triples (rdf-star).
To reproduce the diagram in this page, you have to save the specific visualization rules in this page to a file with .n3 extension and choose it with the 'use custom rules' option. The user interface is really rudimentary so you may want to refresh the page and reload the files if you get stuck.
